### ISSUE TITLE
Notifiche per risposte ai miei commenti

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#16]
Mandare una notifica per risposte ai miei commenti

**Comment by digitalx-dev** [comment]
Vengono già inviate le notifiche appena qualcuno commenta ad un commento.
Abbiamo fatto diverse prove e sono arrivate. Aggiungo un commento al post "Curling a Savigliano" quando puoi commenta così vedo se le ricevo. Lascia anche tu un commento così faccio un reply io.
