### ISSUE TITLE
Comunicazione consumo dati per i video

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#17]
Alcune volte, aprendo un video su connessione Dati Cellulare, arriva un alert che ti avvisa del fatto che consumerai traffico dati... questo alert dovrebbe essere in italiano.
**Edit**: possibilmente eliminare completamente questo alert

**Comment by digitalx-dev** [comment]
Non è possibile. L'alert è di iOS e non vi è modo di disabilitarla perchè dipende dall'operatore che si sta utilizzando. E' in inglese perchè il device ha la lingua inglese impostata.
