### ISSUE TITLE
Momentum scroll su barra categorie

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#2]
Lo scroll sulla barra delle categorie delle edizioni e dei canali dovrebbe avere il classico momentum scroll

**Comment by digitalx-dev** [comment]
Non ho idea di cosa sia il "Momentum scroll" .. è tipo uno scroll smooth?

**Comment by Community-Tech** [comment]
Ahah sì
Applicare la classica smooth friction al termine dello scroll
