### ISSUE TITLE
Impaginazione evento su Post

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#20]
Dare più spazio all'icona del calendario, evitare sovrapposizioni

**Comment by digitalx-dev** [comment]
![simulator screen shot - iphone 7 - 2018-01-11 at 13 41 11](https://user-images.githubusercontent.com/19222118/34825990-1933003a-f6d5-11e7-830a-d9fc29e559d8.png)


Più spazio dove? Puoi allegarmi uno screenshot o più dettagli?
Grazie
