### ISSUE TITLE
Login non funziona

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#23]
Funziona la registrazione ma, se faccio click su esci, poi non riesco più ad entrare (dice che i dati non sono validi)

**Comment by Community-Tech** [comment]
Puoi darmi username e password (se puoi) che hai utilizzato? oppure un elenco di passaggi che hai eseguito perchè sto provando a entrare ed uscire e non mi capita mai.

**Comment by digitalx-dev** [comment]
Puoi darmi username e password (se puoi) che hai utilizzato? oppure un elenco di passaggi che hai eseguito perchè sto provando a entrare ed uscire e non mi capita mai.
