### ISSUE TITLE
Crash su Segui Canali

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#27]
Quando faccio tap su segui o smetto di seguire un canale l'app crasha

**Comment by digitalx-dev** [comment]
Dovrebbe essere la versione vecchia mentre quella inviata venerdì non crasha (issue: https://github.com/Community-Tech/ios/issues/13).

Sei sicuro di avere l'ultima versione?

**Comment by Community-Tech** [comment]
Ho installato l'ultima versione che mi propone TestFlight 1.0 (0.1)
Sono su iPhone 6s - Os 11.2.2

**Comment by digitalx-dev** [comment]
Riesci a spiegarmi più nel dettaglio cosa fai? Non riesco a replicare il problema

**Comment by Community-Tech** [comment]
Semplicemente apro "Cerca Canali" e faccio tap su Segui Già per smettere di seguire il canale...
Però ho notato che l'unico canale che non seguivo (cioè Corriere di Savigliano) funziona correttamente. Tutti gli altri li seguivo già e mi danno quel problema... magari con un reset dei Canali seguiti si risolve

**Comment by Community-Tech** [comment]
Se vuoi ci sentiamo al tel così ti spiego meglio

**Comment by digitalx-dev** [comment]
Ah si il problema dovrebbe essere quello. Prima crashava perchè quando si seguiva un canale inviava al service dei dati in meno. Che utente stai usando? Cosi ti resetto i canali su service

**Comment by Community-Tech** [comment]
giorgio@estroverso.com

Al max resetta tutti i follow  degli utenti esistenti se puoi

Grazie

**Comment by Community-Tech** [comment]
:( Sul mio dispositivo non funziona ancora... Ho visto che hai resettato, ma ora se faccio click su segui non succede nulla...

**Comment by digitalx-dev** [comment]
Ok succedeva anche a me ora. Sono riuscito a trovare il problema e l'ho risolto :)
