### ISSUE TITLE
Gestione offline

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#30]
Se apro l'applicazione quando sono offline la pagina si ferma sullo splash screen e rimane bloccata lì anche se ritorno online. L'unico modo per riaprire l'applicazione è chiuderla (eliminandola dalle operazioni in background) e quindi aprirla.
Chiediamo quindi di ripetere il check sullo stato di connessione fino a che non ritorno online.

**Comment by digitalx-dev** [comment]
E' un errore. Se si è offline dovrebbe atterrare sul login. Controllo
