### ISSUE TITLE
Anagrafica "Canale" da Dashboard Redazione

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#34]
A fondo pagina sotto aggiungi e togli autore per favore inserire casella di testo per _Ulteriori Informazioni_ testo libero fino a 500 caratteri (senza menù formattazione). l'informazione è collocata nelle info del canale sotto gli orari (se compilati) e comunque al fondo dell'ultimo testo disponibile.
grazie

**Comment by digitalx-dev** [comment]
sposta admin: https://github.com/Community-Tech/ios/issues/34
