### ISSUE TITLE
Lunghezza post e titolo

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#37]
I post e i titoli vengono tagliati anche se il limite di caratteri su admin è superiore
Post: 280 caratteri
Titoli: 140
Vedi articolo:
https://communitysmart-services.azurewebsites.net/article/5a782c81149d0333d0f57d3f

Su Android invece è corretto

**Comment by digitalx-dev** [comment]
Il bug è stato correttamente rilevato e verrà fixato nella release successiva al 12/02

**Comment by digitalx-dev** [comment]
Si consiglia di non utilizzare titoli più lunghi di 70-90 caratteri come linea generale per evitare che il titolo diventi esageratamente lungo ed invasivo.
