### ISSUE TITLE
Google Analytics e statistiche

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#40]
Gli strumenti di statistica quali Google Analytics ecc... saranno già implementati dal primo giorno?
Ci mandate poi le credenziali di accesso o ci invitate alla visualizzazione dei dati?

Grazie

**Comment by digitalx-dev** [comment]
Per l'accesso ai dati di google analytics è sufficiente che comunichiate l'indirizzo di un google account attivo, così da condividervi la visualizzazione delle statistiche.

**Comment by Community-Tech** [comment]
communitysmart0@gmail.com

Grazie
