### ISSUE TITLE
Focus sull’input commenti

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#5]
L’azione commenta sul post dovrebbe rimandare all’articolo con anchor ai commenti con focus sull’input e aprire la tastiera.

**Comment by digitalx-dev** [comment]
qual'è la differenza tra questo issue e questo https://github.com/Community-Tech/ios/issues/4

**Comment by Community-Tech** [comment]
La differenza sta nel fatto che se clicco Commenta dovrebbe aprirsi l'articolo, anchor su inizio commenti e aprirsi la tastiera.
Se invece clicco sull'icona (fumetto+numero commenti) dovrebbe aprirsi l'articolo e anchor su inizio commenti (la tastiera non si deve aprire)
