### ISSUE TITLE
App test: Cronologiaarticoli

### ISSUE THREAD

**Issue by Community-Tech** [Community-Tech/ios#67]
L'ultimo articolo inserito va al fondo dell'ultima edizione disponibile...
Se inserisco un articolo nuovo in giornata deve andare a collocarsi in cima al feed...
Grazie.
A.

**Comment by digitalx-dev** [comment]
Attualmente e come sempre se aggiungo l'articolo in edizione va per ultimo (è così da gennaio), mentre se lo aggiungo direttamente in edizione del giorno dalla scheda dell'articolo va per primo. Se poi volete è possibile modificare il comportamento facendo inserire per primo l'articolo anche durante l'aggiunta dalla scheda delle edizioni a vs piacimento.

**Comment by Community-Tech** [comment]
Si, preferiamo modificare il comportamento. L’articolo mettiamolo in cima al feed. Meglio. Grazie.

 

Da: digitalx-dev <notifications@github.com> 
Inviato: venerdì 17 agosto 2018 11:35
A: Community-Tech/ios <ios@noreply.github.com>
Cc: Community-Tech <tech@communitysmart.it>; Author <author@noreply.github.com>
Oggetto: Re: [Community-Tech/ios] App test: Cronologiaarticoli (#67)

 

Attualmente e come sempre se aggiungo l'articolo in edizione va per ultimo (è così da gennaio), mentre se lo aggiungo direttamente in edizione del giorno dalla scheda dell'articolo va per primo. Se poi volete è possibile modificare il comportamento facendo inserire per primo l'articolo anche durante l'aggiunta dalla scheda delle edizioni a vs piacimento.
